name: CI/CD with GitHub Actions

on:
  push:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        poetry-version: ["1.4"]
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        run: |
          python3 -m pip install "ruff>=0.0.241,<=0.0.259"
          python3 -m ruff . --fix
      - name: Formatting w/ black
        run: |
          python3 -m pip install "black>=23.3.0"
          python3 -m black .
